# Generated by Django 5.2 on 2025-04-10 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='uncategorized', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.DateField(default=datetime.datetime(2025, 4, 10, 12, 16, 41, 693277, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
